New user info cookie & unit test
rajasoun/traefik-forward-auth pull request #3
Opened 2020-11-06 12:20 UTC by Mayur-Khante

[1] Added user info cookie holding user information.
[2] Added / Updated unit test.

2020-11-09 11:16 UTC, muly requested changes
please address these minor changes

2020-11-09 11:16 UTC, muly commented on internal/server.go
> +			http.Error(w, "Not authorized", http.StatusUnauthorized)
please change this to 5xx error instead of 4xx

2020-11-09 11:16 UTC, muly commented on internal/provider/oidc.go
> +
please cleanup the empty line at the start of the functions

2020-11-09 11:16 UTC, muly commented on internal/provider/oidc.go
> +
please remove the empty line at the end of the function

2020-11-13 10:14 UTC, muly approved these changes

2020-11-13 14:35 UTC, RamuRChenchaiah approved these changes
Conditional:
1. Error message shall be externalised
2. The debug logs to follow certain format

2020-11-13 14:35 UTC, merged